# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYACo3HSME90ExJOdfQmwkcur0IjauXn
"""

!pip install langgraph langsmith

!pip install langchain langchain_groq langchain_community

from google.colab import userdata
groq_api_key=userdata.get('groq_api_key')
langsmith_api_key=userdata.get('langsmith_api_key')
print(groq_api_key,langsmith_api_key)

import os
os.environ["LANGCHAIN_API_KEY"]=langsmith_api_key
os.environ["LANGCHAIN_TRACKING_V2"]="true"
os.environ["LANGCHAIN_PROJECT"]="TestLanggraph"

from langchain_groq import ChatGroq

llm=ChatGroq(groq_api_key=groq_api_key,model_name='Gemma-9b-It')
llm

"""##Start build chatbot using langgraph"""

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import StateGraph,START,END
from langgraph.graph.message import add_messages

class State(TypedDist):
  messages:Annotated[list,add_messages]
graph_builder=StateGraph(State)

graph_builder

def chatbot(state:State):
  return {"messages":llm.invoke(state['messages'])}



graph_builder.add_node("chatbot",chatbot)

graph_builder.add_edge(START,'chatbot')
graph_builder.add_edge('chatbot',END)

grapg=graph_builder.compile()

from IPython,

while True:
  user_input=input('User: ')
  if user_input.lower() in ['quit','q']:
    print('good bye')
    break
  for event in graph.stream({'messages':('user',user_input)}):
    print(event.values())
    for value in event.values():
      print(values['messages'])
      print("Assistant: ",value['messages'].content)

